echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "Hi I am Steven"
echo "Learning how to use Git and update Github Repo"
echo "Checking uncommitted file status"